defaults:

  update-submodules: &update-submodules
    run:
      name: "Update git submodules"
      command: |
        git submodule update --init

  environment-info: &environment-info
    run:
      name: "Environment info"
      command: |
        echo CXX: $CXX
        echo Generator: $GENERATOR
        echo CMake options: $CMAKE_OPTIONS
        $CXX --version
        $CXX --version >> toolchain
        echo $GENERATOR >> toolchain

  install-system-deps: &install-system-deps
    run:
      name: "Install system dependencies"
      command: |
        sudo apt -q update
        sudo apt -qy install python

  configure: &configure
    run:
      name: "Configure"
      # Build "out-of-source" to have better coverage report
      # (ninja is using relative paths otherwise).
      working_directory: ~/build
      command: |
        cmake ../project -G "$GENERATOR" -DCMAKE_BUILD_TYPE=$BUILD_TYPE $CMAKE_OPTIONS -DEVM2WASM_TOOLS=OFF

  build: &build
    run:
      name: "Build"
      working_directory: ~/build
      command: cmake --build . -- -j $BUILD_PARALLEL_JOBS

  store-hera: &store-hera
    store_artifacts:
      path: ~/build/src/libhera.so
      destination: libhera.so

  save-deps-cache: &save-deps-cache
    cache-save:
      name: "Save dependencies cache"
      key: &deps-cache-key deps-4-{{arch}}-{{checksum "toolchain"}}-{{checksum "cmake/ProjectBinaryen.cmake"}}
      paths:
        - ~/build/deps

  restore-deps-cache: &restore-deps-cache
    cache-restore:
      name: "Restore dependencies cache"
      key: *deps-cache-key

  save-eth-cache: &save-eth-cache
    save_cache:
      key: &eth-cache-key cpp-prebuilt-cache-{{arch}}-{{checksum "toolchain"}}-v1.4.0rc5
      paths:
        - ~/build
        - ~/.hunter

  restore-eth-cache: &restore-eth-cache
    restore_cache:
      key: *eth-cache-key

  checkout-cpp-eth: &checkout-cpp-eth
    run:
      name: "Checkout cpp-ethereum repo"
      working_directory: ~/
      command: |
        git clone https://github.com/ethereum/cpp-ethereum --branch v1.4.0rc5 --single-branch --recurse-submodules --depth 1

  link-hera: &link-hera
    run:
      name: "Link hera to prebuilt cpp-eth"
      working_directory: ~/project
      # TODO: run cmake in hera dir with config flags -DHERA_DEBUGGING=ON
      command: |
        cd ..
        echo "pwd: $(pwd)"
        echo "listing files: $(ls -al)"
        rm -rf ~/cpp-ethereum/hera
        ln -s ~/project ~/cpp-ethereum/hera

  build-cpp-eth: &build-cpp-eth
    run:
      name: "Build cpp-ethereum with linked Hera"
      working_directory: ~/project
      # export PATH is an alternative to `make install`
      command: |
        cd ..
        mkdir -p build && cd build
        cmake ../cpp-ethereum -DCMAKE_BUILD_TYPE=RelWithDebInfo -DHERA=ON
        make -j8
        echo "build finished."
        echo 'export PATH=~/build/test:$PATH' >> $BASH_ENV
        cd ../cpp-ethereum
        echo "cpp-ethereum branch: $(git rev-parse --abbrev-ref HEAD)  commit: $(git rev-parse HEAD)"
        cd hera
        echo "hera branch: $(git rev-parse --abbrev-ref HEAD)  commit: $(git rev-parse HEAD)"

  install-cpp-ethereum: &install-cpp-ethereum
    run:
      name: "Install cpp-ethereum"
      command: |
        URL=https://github.com/ethereum/cpp-ethereum/releases/download/v1.4.0rc5/aleth-1.4.0rc5-linux-x86_64.tar.gz
        curl -L $URL | sudo tar xz -C /usr/local

  fetch-tests: &fetch-tests
    run:
      name: "Fetch eWASM tests"
      command: |
        git clone https://github.com/ewasm/tests -b wasm-tests --single-branch --depth 1

  test: &test
    run:
      name: "Test shared Hera"
      command: |
        testeth --version
        testeth -t GeneralStateTests/stEWASMTests -- --testpath tests --vm ~/build/src/libhera.so --singlenet Byzantium --evmc engine=binaryen

  test-wabt: &test-wabt
    run:
      name: "Test shared Hera (wabt)"
      command: |
        testeth --version
        testeth -t GeneralStateTests/stEWASMTests -- --testpath tests --vm ~/build/src/libhera.so --singlenet Byzantium --singletest "useGas" --evmc engine=wabt
        testeth -t GeneralStateTests/stEWASMTests -- --testpath tests --vm ~/build/src/libhera.so --singlenet Byzantium --singletest "createFromTransaction" --evmc engine=wabt

  evmc-test: &evmc-test
    run:
      name: "Run evmc tests"
      command: |
        ~/build/evmc/test/evmc-vmtester ~/build/src/libhera.so

  evm2wasm-test: &evm2wasm-test
    run:
      name: "Run evm2wasm state tests"
      command: |
        testeth --version
        testeth -t GeneralStateTests/stExample -- --testpath tests --vm ~/build/src/libhera.so --singlenet Byzantium --singletest "add11" --evmc evm1mode=evm2wasm.cpp
        testeth -t GeneralStateTests/stStackTests -- --testpath tests --vm ~/build/src/libhera.so --singlenet Byzantium --evmc evm1mode=evm2wasm.cpp

  upload-coverage-data: &upload-coverage-data
    run:
      name: "Upload coverage data"
      command: |
        codecov --required --gcov-root ~/build --gcov-exec gcov-6


version: 2
jobs:
  linux-clang-shared-release:
    environment:
      - BUILD_TYPE: Release
      - CXX: clang++
      - CC:  clang
      - GENERATOR: Ninja
      - BUILD_PARALLEL_JOBS: 4
      - CMAKE_OPTIONS: -DBUILD_SHARED_LIBS=ON -DHERA_DEBUGGING=OFF -DHERA_WAVM=ON -DHERA_WABT=ON -DEVMC_TESTING=ON
    docker:
      - image: ethereum/cpp-build-env:3
    steps:
      - *install-system-deps
      - checkout
      - *update-submodules
      - *environment-info
      - *restore-deps-cache
      - *configure
      - *build
      - *save-deps-cache
      - *install-cpp-ethereum
      - *store-hera
      - *fetch-tests
      - *test
      - *test-wabt
      - *evmc-test
      - *evm2wasm-test

  linux-gcc-shared-coverage:
    environment:
      - BUILD_TYPE: Debug
      - CXX: g++
      - CC:  gcc
      - GENERATOR: Ninja
      - BUILD_PARALLEL_JOBS: 4
      - CMAKE_OPTIONS: -DCOVERAGE=ON -DBUILD_SHARED_LIBS=ON -DHERA_DEBUGGING=ON
    docker:
      - image: ethereum/cpp-build-env
    steps:
      - *install-system-deps
      - checkout
      - *update-submodules
      - *environment-info
      - *restore-deps-cache
      - *configure
      - *build
      - *save-deps-cache
      - *install-cpp-ethereum
      - *store-hera
      - *fetch-tests
      - *test
      - *upload-coverage-data

  linux-gcc-debug:
    environment:
      - BUILD_TYPE: Debug
      - CXX: g++
      - CC:  gcc
      - GENERATOR: Unix Makefiles
      - BUILD_PARALLEL_JOBS: 4
      - CMAKE_OPTIONS: -DHERA_DEBUGGING=ON -DHERA_WAVM=ON -DHERA_WABT=ON
    docker:
      - image: ethereum/cpp-build-env
    steps:
      - *install-system-deps
      - checkout
      - *update-submodules
      - *environment-info
      - *restore-deps-cache
      - *configure
      - *build
      - *save-deps-cache

workflows:
  version: 2
  hera:
    jobs:
      - linux-clang-shared-release
      - linux-gcc-shared-coverage
      - linux-gcc-debug
